--
-- Copyright 2014 Comcast Cable Communications Management, LLC
--
-- This file is part of CATS.
--
-- CATS is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- CATS is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with CATS.  If not, see <http://www.gnu.org/licenses/>.
--

--Created using /video-recorder-service/src/test/java/com/comcast/cats/recorder/persistence/SqlTableCreator.java
alter table pvr_media_info drop constraint FKE3022B1C57118F1D;
drop table pvr_media_info if exists;
drop table pvr_recording if exists;
drop table pvr_recording_status if exists;
create table pvr_media_info (id integer generated by default as identity (start with 1), created_time timestamp, file_path varchar(255), http_path varchar(255), last_updated_time timestamp, primary key (id));
create table pvr_recording (id integer generated by default as identity (start with 1), created_time timestamp, last_updated_time timestamp, mrl varchar(255), stb_mac_address varchar(255), video_server_ip varchar(255), video_server_port integer, primary key (id));
create table pvr_recording_status (id integer generated by default as identity (start with 1), message varchar(255), status_code varchar(255), primary key (id));
alter table pvr_media_info add constraint FKE3022B1C57118F1D foreign key (id) references pvr_recording;
